### PR TITLE
Updated to latest gpipe/gpipe-glfw

### PR DESCRIPTION
**Pull request by ghost**
Kind of messy, since there were some intermediate changes.

Here's a preview: http://imgur.com/a/BRTqh

Comparing it with the version on master which I'd kept around on my system there's clearly some issues with texture rendering (as you can see in the gifv).

### CODE REVIEW

**Comment by ghost** [comment]
@tobbebex try it out

**Comment by plredmond** [comment]
i just compared with the master version which i'd kept around on my system.. there's clearly some issues with texture rendering (as you can see in the gifv)

**Comment by ghost** [comment]
The build failed because travis is overriding the resolver specified in the `stack.yaml` file.

```
...
Downloaded nightly-2016-01-30 build plan.
...
```

The `stack.yaml` uses a nightly from this year.

**Comment by csabahruska** [comment]
Thanks.

**Comment by csabahruska** [comment]
You mentioned previously that the rendering is faster. What did you mean?

**Comment by ghost** [comment]
I wrote that based on my memory of the old version, running on a different machine. Running both versions on my current machine, I don't see any difference. So I deleted the comment.

**Pull request merged**
