### PR TITLE
Optimization: Concatenating PrimitiveArrays

### PR DESCRIPTION
**Pull request by tobbebex**
This optimization merges all PrimitiveArrays in each render queue, so that all patches are first rendered with pass 1, then pass 2, etc, instead of constantly switching passes. In order to do this, I made the array of lightmap textures into a Texture2DArray instead, and inserted the index into this array into each patches PrimitiveArray before concatenating (using the new ToVertex Float instance from GPipe 2.1.6) so that the right lightmap can be selected during shader execution.

This optimization reduces number of GL-calls from 120k to 20k, so a reduction of more than 80%! Each drawcall is now much cheaper, but the number of drawcalls doesn't change with this (4222(!)). The next step would be to attack that, eg by BSP-tree culling.

### CODE REVIEW

**Comment by tobbebex** [comment]
Worth mentioning is that I haven't released GPipe 2.1.6 yet, so you'll have to sync the github repo for that :)

**Comment by csabahruska** [comment]
No problem!
In the optimized version the lightmap seem to be wron in some places.
Is it correct in your machine?
gpipe-quake3-lightmap-bug

**Comment by tobbebex** [comment]
Oops, should be fixed on HEAD of GPipe-Core now.

**Comment by tobbebex** [comment]
The bug I just fixed pushed up GL API call count to 25k...

**Comment by tobbebex** [comment]
Hm, found more bugs, but this time in the changes I made to your code, will fix and send another pull request

**Pull request merged**
