### PR TITLE
Fixed bug where I had deleted white texture while it was still needed

### PR DESCRIPTION
**Pull request by tobbebex**
Now it actually looks like it did before my optimizations

### CODE REVIEW

**Comment by csabahruska** [comment]
It looks better but still not 100% accurate :)
with optimization:
gpipe-quake3-lightmap-bug2
original:
gpipe-quake3-lightmap-ok

**Comment by tobbebex** [comment]
Did you also sync latest from GPipe-Core? Mine look like the lower one with optimizations now

**Comment by csabahruska** [comment]
Yes, i'm on head on master branch (https://github.com/tobbebex/GPipe-Core/commit/d5cb4cdf1fdc7fd4e2a4b7582e7c12ff430b80d8).

**Comment by csabahruska** [comment]
It works, Thanks.

**Comment by tobbebex** [comment]
I just did some more optimizations in GPipe-Core so you should try latest now. Quite good given that it is running over 4000 DCs :)

**Pull request merged**
